### ISSUE TITLE
`update-linker` could be an automated check (only run every 24 hours) that runs on the background

### ISSUE THREAD

**Issue by eordano** [decentraland/cli#10]

**Comment by michaltakac** [comment]
Copy-pasting a chat where we were discussing this:

**cazala** 3:49 PM
@michaltakac when does the user have to run the `upgrade` command?

**michaltakac** 4:04 PM
if there's a newer version of linker app (and I don't know when there will be a need for updating visuals of the page after github.com/decentraland/cli/issues/15 is finished)
 
so in theory, even manual upgrading is fine because it won't be much needed (contract address is automatically updated because we rely on `https://decentraland.github.io/contracts/addresses.json`)

**michaltakac** 4:15 PM
and what we can do is to add `isOutdated()` checker whenever you run `dcl {{command}}` within DCL project and if it returns `true`, it will log a message `The Ethereum linker app is outdated. Please update it by running dcl upgrade.`

**Comment by michaltakac** [comment]
Closed #10 through #47.
