### ISSUE TITLE
dcl preview does not work with new dcl init project on ubuntu

### ISSUE THREAD

**Issue by jschiarizzi** [decentraland/cli#176]
## OS
Ubuntu 17.10

## Error
![cli preview error](https://user-images.githubusercontent.com/9449596/42050992-957541e4-7ad8-11e8-860d-66c7b3227dd4.png)

## Steps to reproduce: 
$ cli init
$ cli preview

## steps to solve
$ echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
$ sudo sysctl --system

**Comment by hugoArregui** [comment]
I could reproduce it too in Arch, the problem is although some combination of files and directories are ignored (the ones in `.dcignore`), *all* files are being watched (including, for example, `node_modules` files). See: https://github.com/decentraland/cli/blob/master/src/lib/Preview.ts#L52

`chokidar` accepts an `ignored` parameter, and by using it we can not only fix the problem but also improve efficiency since less files are going to be watched, the problem is AFAIC the `ignored` format is not compatible with the git ignore format used in the `.dcignore` (or in node-ignore for that matter).

So, options I can think of:

- A little hack, `node-ignore` library keeps a list of rules internally (a list of regexps) so you can actually use that in chokidar. Not really a good solution but it's a quick and easy workaround (I fixed it on my local this way).
- Add support for `node-ignore` in `chokidar`.
- Deprecate the git format and use glob patterns instead.

**Comment by belohlavek** [comment]
@hugoArregui can you send a PR with your walkaround? From there on we can have a short discussion about dropping the .dclignore format (although it's intuitive).

Sorry for the delay, I haven't been on top of the CLI lately!

**Comment by hugoArregui** [comment]
@belohlavek I don't think it should be actually applied because it might fail if someone is using negative patterns or some weird stuff. I was just suggesting it as a local workaround so people can continue working.

I never sent the actual code so I'm pasting it here so people can copy&paste:

```
        const rules = ig['_rules'].map((rule) => rule.regex);
        chokidar.watch(root, { ignored: rules }).on('all', (event, path) => {
```

I'm not super familiar with the code and I need to explore it further before saying something useful but IMHO it will be nice to drop dcignore and build something using nodemon, which provides the ability to be hook to whatever the user wants to define.
