### ISSUE TITLE
How to initialize Babylon.js Engine without access to the DOM?

### ISSUE THREAD

**Issue by damo1884** [decentraland/cli#234]
Example that demonstrates using Babylon.js + Physics Engine in a scene

Supported Physics Engines:
- Cannon.js - a wonderful physics engine written entirely in JavaScript
- Oimo.js - a JS port of the lightweight Oimo physics engine

Example Scene: https://playground.babylonjs.com/frame.html#7149G4#0
Example Tutorial: https://doc.babylonjs.com/how_to/using_the_physics_engine#how-to-use-a-physics-engine

Currently there is no way that I can see to initialize the engine without a reference to the DOM

For example this throws an error 'document.getElementById' as document is undefined

```
var canvas = document.getElementById("renderCanvas") as HTMLCanvasElement; // Get the canvas element 
var engine = new BABYLON.Engine(canvas, true); // Generate the BABYLON 3D engine
```

How can I pass the DOM element to the Babylon engine inside scene.tsx?

**Comment by fmiras** [comment]
@damo1884 why do you want to initialize the Babylon.JS engine? Our SDK stands to bring you the tools that you need to build your scene, behind all this tools we're using Babylon as our engine but you can't access it. This is because both our SDK and Decentraland scenes need to be agnostic of what engine we're using in case we change it.
