### ISSUE TITLE
`dcl build` == `npm run build`

### ISSUE THREAD

**Issue by eordano** [decentraland/cli#428]
Why don't we have a `dcl build` command?

**Comment by nearnshaw** [comment]
Something like that would help for our own deployments from the scene pool.

I know Juanca is working on a flow for downloading scenes from the builder, assigning them a set of free parcels from the pool, and then runs a script that deploys them all in batch. The problem is that right now it's necessary to first run a `dcl start` before deploying. A `dcl build` would make that batch process easier.

**Comment by fmiras** [comment]
@nearnshaw it isn't necessary you can just run `npm run build` I already talked to him.

@eordano I really don't see the point of that. We can still add it easily

**Comment by eordano** [comment]
It's counter-intuitive to delegate this to a different `cli`.

It's like doing `npm init` and then `make start`...

**Comment by fmiras** [comment]
I don't think that is like that, is more like `create-react-app`, you don't build stuff by running `create-react-app build` is a boilerplate generator and a tool, `dcl` is to `decentraland-ecs` what CRA is to `react`

**Comment by eordano** [comment]
With all the "info" commands I'd say it's a little more than that!
Nevertheless, it's something many of us had noticed.
