### ISSUE TITLE
Verification for renderer

### ISSUE THREAD

**Issue by menduz** [decentraland/cli#55]
How do we verify that the parcels in `scene.json#scene.parcels` belong to the same user that is publishing the parcel?

**Comment by cazala** [comment]
we could check this when linking to ethereum but nothing would stop you from modifying the `scene.json` and reuploading to ipfs / updating ipns. we should also enforce this on the client side.

**Comment by bnolan** [comment]
We need to query all the parcels and they must all link to the same IPFS / IPNS hash. There is a potential for abuse here because a parcel might specify that it across 1000s of parcels, and we would query for all of them thus DDOSing the ethereum node.

The other problem is that if someone owns multiple parcels, they can have a valid multi-parcel and an invalid multi-parcel in the same area. For example:


```
| 0 | 1 | 2 | 3 | 4 | 5 |
| A | A | B | B | B | B |
```

In this case, multi-parcel A may be accurate (the ipfs hash points at a valid parcel), but multi-parcel B may not be valid (because it specifies that it is parcels 0-5, and the ipfs hash for 0 and 1 do not match), so in this case we need to not display parcel B, but still load parcel A (this is an implementation detail to keep in mind when implementing the multi-parcel ipfs test).

**Comment by bnolan** [comment]
@menduz can this issue be closed, is it just a discussion issue?

Currently we don't verify that the user owns the parcels they are trying to use in the CLI, we assume they are using the CLI correctly, otherwise they will fail at the stage where they publish to the ethereum contract.
