### ISSUE TITLE
"dcl start" not showing server info on WSL2

### ISSUE THREAD

**Issue by juanigallo** [decentraland/cli#648]
# What? 

When running `dcl start` on an empty scene, the server info is empty

### Dev env
- Windows with WSL2
- NodeJS 16.14

### Relevant info
I dont have a tunnel for 127.0.0.1 (I think that this is the default config in WSL) to use it with WSL so my browser is rejecting the connection, to make it work. To make the preview work I need to change it directly in the browser to `localhost:8000`. Dont know if its related but might help

![image](https://user-images.githubusercontent.com/4969737/157317946-27ce01e8-74a6-4cfd-ba70-a8154bac6539.png)

**Comment by leanmendoza** [comment]
Thank for reporting, I just checked on Mac and it isn't working neither.
<img width="619" alt="image" src="https://user-images.githubusercontent.com/8042536/157343636-6a1e52d9-6e8d-40f0-8497-97c89162acf4.png">

Same major node version  => v16.13.1
And CLI 3.9.1

Which CLI version is this happening you? Because it hasn't reported until now I think.

**Comment by juanigallo** [comment]
I have 3.9.0, didn't try with a downgrade because it was non blocker for me
