### ISSUE TITLE
dcl start javascript errors - voice chat not working

### ISSUE THREAD

**Issue by psankar07** [decentraland/cli#670]
when run dcl start for any scene, chrome loads scene with bunch of javascript error.

<img width="1609" alt="Screen Shot 2022-04-10 at 11 16 31 PM" src="https://user-images.githubusercontent.com/48458771/162676651-b971d174-a4df-4954-8211-de8a270d86df.png">

Not sure, if this is a reason for voice chat not woking in localhost realm.

**Comment by nearnshaw** [comment]
Hey @psankar07 
Voice chat is not currently supported when running a local scene. There are plans for adding support for that, it's part of a big project to remake of comms. 

Up until recently there wasn't a real use case for needing this feature in a local scene, although now that you can upload a preview to a 3rd party server like Heroku, it makes sense.

I'll close this issue because it depends on efforts that are not on the CLI side.
